name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run security audit
      run: npm audit --audit-level=high
      
    - name: Check for outdated dependencies
      run: npm outdated || true
      
    - name: Test server functionality
      run: |
        # Start server in background
        npm start &
        SERVER_PID=$!
        echo "Started server with PID: $SERVER_PID"
        
        # Wait for server to start
        sleep 8
        
        # Test health check endpoint
        echo "Testing health check..."
        curl -f http://localhost:3000/ || exit 1
        
        # Test basic placeholder generation
        echo "Testing basic placeholder..."
        curl -f -o test-image.png "http://localhost:3000/placeholder?size=100x100" || exit 1
        
        # Test with custom parameters
        echo "Testing custom parameters..."
        curl -f -o test-image2.jpg "http://localhost:3000/placeholder?size=200x150&bg=ff6b6b&color=ffffff&format=jpg" || exit 1
        
        # Test alternative URL format
        echo "Testing alternative URL format..."
        curl -f -o test-alt.png "http://localhost:3000/300x200?bg=blue" || exit 1
        
        # Clean up server process
        echo "Cleaning up server process..."
        kill $SERVER_PID || true
        wait $SERVER_PID 2>/dev/null || true
        
        # Clean up test files
        rm -f test-image.png test-image2.jpg test-alt.png
        
        echo "All tests completed successfully!"